[package]
name = "hyperrust"
version = "0.0.1"
edition = "2021"
description = "RGB utility for HyperX Alloy Origins 60 keyboard"
license = "MIT"
repository = "https://github.com/EriksRemess/hyperrust"
readme = "README.md"
keywords = ["hyperx", "keyboard", "rgb", "cli", "utility"]
categories = ["command-line-utilities", "hardware-support"]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
crossterm = "0.28.1"
hidapi = "2.6.3"
rand = "0.8.5"
